// <auto-generated />
using System;
using ApiUniversidade.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace apiUniversidade.Migrations
{
    [DbContext(typeof(ApiUniversidadeContext))]
    partial class ApiUniversidadeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Escola.Model.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datanascimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("alunos");
                });

            modelBuilder.Entity("Escola.Model.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("alunoid");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("area");

                    b.Property<int>("Duracao")
                        .HasColumnType("integer")
                        .HasColumnName("duracao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("cursos");
                });

            modelBuilder.Entity("Escola.Model.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("alunoid");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("integer")
                        .HasColumnName("cargahoraria");

                    b.Property<int?>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("cursoid");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Semestre")
                        .HasColumnType("integer")
                        .HasColumnName("semestre");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("CursoId");

                    b.ToTable("disciplinas");
                });

            modelBuilder.Entity("Escola.Model.Curso", b =>
                {
                    b.HasOne("Escola.Model.Aluno", null)
                        .WithMany("cursos")
                        .HasForeignKey("AlunoId");
                });

            modelBuilder.Entity("Escola.Model.Disciplina", b =>
                {
                    b.HasOne("Escola.Model.Aluno", null)
                        .WithMany("disciplinas")
                        .HasForeignKey("AlunoId");

                    b.HasOne("Escola.Model.Curso", null)
                        .WithMany("disciplinas")
                        .HasForeignKey("CursoId");
                });

            modelBuilder.Entity("Escola.Model.Aluno", b =>
                {
                    b.Navigation("cursos");

                    b.Navigation("disciplinas");
                });

            modelBuilder.Entity("Escola.Model.Curso", b =>
                {
                    b.Navigation("disciplinas");
                });
#pragma warning restore 612, 618
        }
    }
}
